const DATA_URL='data.json';
const app=document.getElementById('app');
const toastEl=document.getElementById('toast');
const KEYS={theme:'seTheme',profile:'seProfile',teachers:'seTeachers',papers:'sePapers',results:'seResults'};
let data=null,state={view:'home',classId:null,semester:1,subject:null,role:null,practiceIndex:0,practiceAnswers:{},examIndex:0,examAnswers:{},examStarted:false,timer:null};

const $=(s,r=document)=>r.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function showToast(msg){toastEl.textContent=msg;toastEl.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toastEl.classList.remove('show'),2200)}
function setTheme(){document.body.classList.toggle('dark',localStorage.getItem(KEYS.theme)==='dark');$('#themeBtn').textContent=document.body.classList.contains('dark')?'☀':'☾'}
function nav(view,extra={}){clearInterval(state.timer);state={...state,view,...extra,practiceIndex:0,practiceAnswers:{},examIndex:0,examAnswers:{},examStarted:false,timer:null};render()}
function classById(id){return data.classes.find(x=>x.id===id)}
function subjectKey(){return `${state.classId}|${state.semester}|${state.subject}`}
function questionsFor(k=subjectKey()){return (data.questions[k]||[]).map(q=>({...q,options:q.options||[],answer:Number(q.answer??0)}))}
function defaultQuestions(){return [
 {type:'mcq',q:'এখানে আপনার প্রশ্ন লিখুন।',options:['বিকল্প ১','বিকল্প ২','বিকল্প ৩','বিকল্প ৪'],answer:0,solution:'সঠিক উত্তরটি প্রশ্ন তৈরির সময় নির্ধারণ করা যাবে।'}
]}
function render(){setTheme();switch(state.view){case'home':return renderHome();case'class':return renderClass();case'practice':return renderPractice();case'solutions':return renderSolutions();case'teacher':return renderTeacher();case'teacherBuilder':return renderBuilder();case'student':return renderStudent();case'studentExam':return renderExam();case'result':return renderResult();case'computer':return renderComputer();case'profile':return renderProfile();default:return renderHome()}}
function headerBack(title){return `<div class="toolbar"><button class="secondary" data-action="back">← Back</button><h2>${esc(title)}</h2><span></span></div>`}
function renderHome(){app.innerHTML=`<div class="page">
<section class="hero"><div><p class="eyebrow">SMART LEARNING • MODEL QUESTIONS • PRACTICE</p><h1>Let’s start a <span>smart class</span><br>with AKS</h1><p>Class 5 থেকে Class 12 পর্যন্ত সাজানো প্রশ্ন, Model Set, Practice এবং Solution এক জায়গায়।</p></div><div class="hero-art"><span class="hero-cap">◆</span></div></section>
<section class="section"><div class="section-head"><div><p class="eyebrow">CHOOSE YOUR MODE</p><h2>Student, Teacher or Computer</h2></div></div><input class="search" id="homeSearch" placeholder="Search your class, subject or school...">
<div class="role-grid"><button class="role-card" data-action="student"><div class="role-icon">🎓</div><h3>Student</h3><p>Teacher Code দিয়ে paper দেখুন, Practice করুন এবং Exam দিন।</p></button><button class="role-card" data-action="teacher"><div class="role-icon">👨‍🏫</div><h3>Teacher</h3><p>Question paper তৈরি, save, share এবং student result দেখুন।</p></button><button class="role-card" data-action="computer"><div class="role-icon">💻</div><h3>Computer</h3><p>Computer learning room, practice এবং math questions।</p></button></div></section>
<section class="section"><p class="eyebrow">EXPLORE</p><h2>Choose your class</h2><div class="class-grid" id="classGrid">${data.classes.map(c=>classCard(c)).join('')}</div></section></div>`;$('#homeSearch').addEventListener('input',filterClasses)}
function classCard(c){return `<button class="class-card" data-class="${c.id}"><div class="book-icon">${c.icon}</div><h3>${esc(c.name)}</h3><p>${c.subjects} Subjects • 4 Semesters</p><p>${(data.subjects[c.id]||[]).slice(0,4).join(' • ')}<br>Science+${Math.max(0,c.subjects-4)} more</p><span class="arrow">→</span></button>`}
function filterClasses(e){const q=e.target.value.toLowerCase();document.querySelectorAll('#classGrid .class-card').forEach(el=>el.style.display=el.innerText.toLowerCase().includes(q)?'flex':'none')}
function renderClass(){const c=classById(state.classId);const subs=data.subjects[state.classId]||[];app.innerHTML=`<div class="page">${headerBack(c?.name||'Class')}<p class="eyebrow">PRACTICE SUBJECTS</p><h1>${esc(c?.name||'Class')} — Practice Subjects</h1><p class="muted">প্রতিটি Class + Semester + Subject-এর প্রশ্ন আলাদা। এটি শুধু Practice-এর জন্য।</p><div class="panel"><div class="field"><label>Semester</label><select id="semester">${[1,2,3,4].map(x=>`<option value="${x}" ${x==state.semester?'selected':''}>${x}</option>`).join('')}</select></div></div><div class="subject-grid">${subs.map(s=>subjectCard(s)).join('')}</div></div>`;$('#semester').addEventListener('change',e=>{state.semester=Number(e.target.value);state.subject=null;render()})}
function subjectIcon(s){if(s.includes('বাংলা'))return'📖';if(s.includes('ইংরেজি'))return'🔤';if(s.includes('Physics'))return'⚛️';if(s.includes('Life'))return'🧬';if(s.includes('গণিত')||s.includes('Account'))return'➗';if(s.includes('Geography'))return'🌍';if(s.includes('History'))return'🏛️';if(s.includes('Computer'))return'💻';return'📚'}
function subjectCard(s){const count=questionsFor(`${state.classId}|${state.semester}|${s}`).length;return `<article class="subject-card"><div class="subject-icon">${subjectIcon(s)}</div><h3>${esc(s)}</h3><p>${esc(s)} • Semester ${state.semester}</p><p>${count?count+' questions available':'Questions ready to add'}</p><div class="action-row"><button class="primary" data-practice="${esc(s)}">Practice →</button><button class="secondary" data-solutions="${esc(s)}">Solutions</button></div></article>`}
function renderPractice(){const qs=questionsFor();app.innerHTML=`<div class="page">${headerBack(`${state.subject} • Semester ${state.semester}`)}<div class="toolbar"><div><p class="eyebrow">PRACTICE</p><h1>${esc(state.subject)}</h1></div><span class="badge">${qs.length} Questions</span></div><div id="practiceList" class="question-list">${qs.length?qs.map((q,i)=>questionHTML(q,i,'practice')).join(''):emptyQuestions()}</div></div>`}
function emptyQuestions(){return `<div class="empty"><h3>এই Subject-এর প্রশ্ন এখনো নেই</h3><p>Teacher Question Builder থেকে প্রশ্ন Save/Publish করলে এখানে আসবে।</p><button class="primary" data-action="teacherBuilder">Question তৈরি করুন</button></div>`}
function questionHTML(q,i,mode){const chosen=mode==='practice'?state.practiceAnswers[i]:state.examAnswers[i];return `<article class="question-card"><div class="q-head"><span class="badge">Question ${i+1}</span><span class="muted">MCQ</span></div><h3>${esc(q.q)}</h3>${q.options.map((o,j)=>`<div class="option ${chosen===j?'selected':''}" data-answer-mode="${mode}" data-q="${i}" data-opt="${j}">${esc(o)}</div>`).join('')} ${mode==='practice'&&chosen!==undefined?`<div class="solution"><b>${chosen===q.answer?'✓ সঠিক':'✗ ভুল'}</b><br>${esc(q.solution||'No solution')}</div>`:''}</article>`}
function renderSolutions(){const qs=questionsFor();app.innerHTML=`<div class="page">${headerBack(`${state.subject} • Solutions`)}<p class="eyebrow">SOLUTIONS</p><h1>Solutions</h1><div class="question-list">${qs.length?qs.map((q,i)=>`<article class="question-card"><span class="badge">Question ${i+1}</span><h3>${esc(q.q)}</h3><div class="solution"><b>Answer:</b> ${esc(q.options[q.answer]||'')}<br>${esc(q.solution||'')}</div></article>`).join(''):emptyQuestions()}</div></div>`}
function renderTeacher(){app.innerHTML=`<div class="page">${headerBack('Teacher')}<div class="panel"><p class="eyebrow">TEACHER</p><h1>Create & Manage Questions</h1><p class="muted">Teacher information save করুন, তারপর ২০টি পর্যন্ত MCQ paper তৈরি করে share code বানান।</p><form id="teacherForm" class="form-grid"><div class="field"><label>Teacher Name</label><input id="tName" required placeholder="Teacher Name"></div><div class="field"><label>Teacher Code / School Code</label><input id="tCode" placeholder="যেমন TEACHER01"></div><div class="field"><label>Class</label><select id="tClass">${data.classes.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Semester</label><select id="tSem">${[1,2,3,4].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field full"><label>Subject</label><select id="tSub"></select></div><div class="field full"><button class="primary">Save & Continue →</button></div></form></div><div class="panel"><h2>Saved Teacher Papers</h2><div id="teacherPapers" class="list">${teacherList()}</div></div></div>`;bindTeacherSubjects();$('#teacherForm').addEventListener('submit',saveTeacher)}
function bindTeacherSubjects(){const c=$('#tClass').value;$('#tSub').innerHTML=(data.subjects[c]||[]).map(s=>`<option>${esc(s)}</option>`).join('');$('#tClass').addEventListener('change',e=>{$('#tSub').innerHTML=(data.subjects[e.target.value]||[]).map(s=>`<option>${esc(s)}</option>`).join('')})}
function saveTeacher(e){e.preventDefault();const teacher={id:crypto.randomUUID(),name:$('#tName').value.trim(),code:($('#tCode').value.trim()||'').toUpperCase(),classId:$('#tClass').value,semester:Number($('#tSem').value),subject:$('#tSub').value};if(!teacher.name)return;const arr=read(KEYS.teachers,[]);arr.unshift(teacher);write(KEYS.teachers,arr);state.teacher=teacher;nav('teacherBuilder',{teacher})}
function teacherList(){const arr=read(KEYS.papers,[]);if(!arr.length)return `<div class="empty">কোনো paper তৈরি হয়নি।</div>`;return arr.slice(0,8).map(p=>`<div class="list-item"><div><b>${esc(p.title)}</b><br><span class="small muted">${esc(p.teacherName)} • ${esc(p.className)} • Semester ${p.semester}</span></div><button class="secondary" data-paper="${p.id}">Open</button></div>`).join('')}
function renderBuilder(){const t=state.teacher||read(KEYS.teachers,[])[0];if(!t)return nav('teacher');const key=`${t.classId}|${t.semester}|${t.subject}`;let existing=read(KEYS.papers,[]).find(p=>p.teacherId===t.id&&p.classId===t.classId&&p.semester===t.semester&&p.subject===t.subject);if(!state.builderQs)state.builderQs=existing?.questions?.length?existing.questions:[];app.innerHTML=`<div class="page">${headerBack('Teacher Question Builder')}<div class="panel"><p class="eyebrow">QUESTION PAPER</p><h1>${esc(t.subject)}</h1><p class="muted">${esc(t.name)} • ${esc(classById(t.classId)?.name)} • Semester ${t.semester}</p><div class="notice">সর্বোচ্চ ২০টি প্রশ্ন। Save করলে Teacher Paper list-এ থাকবে এবং Share Code তৈরি হবে।</div><div class="toolbar"><h2>${state.builderQs.length} / 20 Questions</h2><button class="primary" data-action="addQuestion">＋ Add Question</button></div><div class="question-list">${state.builderQs.map((q,i)=>builderQ(q,i)).join('')||'<div class="empty">＋ Add Question চাপুন।</div>'}</div><div class="action-row"><button class="primary" data-action="savePaper">SAVE & CREATE SHARE CODE</button><button class="secondary" data-action="teacher">Back</button></div></div></div>`}
function builderQ(q,i){return `<article class="question-card"><div class="q-head"><span class="badge">Question ${i+1}</span><button class="danger-btn" data-delete-q="${i}">Delete</button></div><div class="field"><label>Question</label><textarea data-edit-q="${i}" data-field="q" rows="3">${esc(q.q||'')}</textarea></div><div class="form-grid" style="margin-top:12px">${(q.options||['','','','']).map((o,j)=>`<div class="field"><label>Option ${j+1}</label><input data-edit-q="${i}" data-opt="${j}" value="${esc(o)}"></div>`).join('')}<div class="field"><label>Correct option</label><select data-edit-q="${i}" data-field="answer">${[0,1,2,3].map(x=>`<option value="${x}" ${Number(q.answer)===x?'selected':''}>Option ${x+1}</option>`).join('')}</select></div><div class="field full"><label>Solution</label><input data-edit-q="${i}" data-field="solution" value="${esc(q.solution||'')}"></div></div></article>`}
function syncBuilder(){document.querySelectorAll('[data-edit-q]').forEach(el=>{const i=Number(el.dataset.editQ);if(!state.builderQs[i])return;if(el.dataset.opt!==undefined)state.builderQs[i].options[Number(el.dataset.opt)]=el.value;else if(el.dataset.field==='answer')state.builderQs[i].answer=Number(el.value);else state.builderQs[i][el.dataset.field]=el.value})}
async function makeShareCode(payload){const json=JSON.stringify(payload);try{if('CompressionStream'in window){const cs=new CompressionStream('deflate');const writer=cs.writable.getWriter();writer.write(new TextEncoder().encode(json));writer.close();const buf=await new Response(cs.readable).arrayBuffer();return 'SE1-'+bytesToB64(new Uint8Array(buf))} }catch{}return 'SE0-'+btoa(unescape(encodeURIComponent(json)))}
function bytesToB64(bytes){let bin='';const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)bin+=String.fromCharCode(...bytes.subarray(i,i+chunk));return btoa(bin).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function b64ToBytes(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const bin=atob(s);return Uint8Array.from(bin,c=>c.charCodeAt(0))}
async function decodeShareCode(code){if(code.startsWith('SE1-')){const ds=new DecompressionStream('deflate');const w=ds.writable.getWriter();w.write(b64ToBytes(code.slice(4)));w.close();return JSON.parse(new TextDecoder().decode(await new Response(ds.readable).arrayBuffer()))}if(code.startsWith('SE0-'))return JSON.parse(decodeURIComponent(escape(atob(code.slice(4)))));return null}
async function savePaper(){syncBuilder();const t=state.teacher;if(!t||!state.builderQs.length)return showToast('কমপক্ষে ১টি প্রশ্ন যোগ করুন');const clean=state.builderQs.slice(0,20).map(q=>({type:'mcq',q:String(q.q||'').trim(),options:(q.options||[]).map(String),answer:Number(q.answer)||0,solution:String(q.solution||'')}));if(clean.some(q=>!q.q||q.options.some(x=>!x)))return showToast('সব প্রশ্ন ও ৪টি option পূরণ করুন');const payload={version:1,teacher:{name:t.name,code:t.code,classId:t.classId,semester:t.semester,subject:t.subject},questions:clean,createdAt:Date.now()};const share=await makeShareCode(payload);const paper={id:crypto.randomUUID(),title:`${t.subject} • ${classById(t.classId).name} • Semester ${t.semester}`,teacherId:t.id,teacherName:t.name,teacherCode:t.code,classId:t.classId,className:classById(t.classId).name,semester:t.semester,subject:t.subject,questions:clean,shareCode:share};const arr=read(KEYS.papers,[]).filter(p=>p.id!==paper.id);arr.unshift(paper);write(KEYS.papers,arr);state.builderQs=clean;render();showToast('Paper saved এবং Share Code তৈরি হয়েছে')}
function renderStudent(){app.innerHTML=`<div class="page">${headerBack('Student')}<div class="panel"><p class="eyebrow">STUDENT</p><h1>Teacher Paper</h1><p class="muted">Teacher-এর Share Code এখানে দিন। এই code অন্য ফোনেও কাজ করতে পারে, কারণ paper-এর data code-এর ভিতরে রাখা হয়।</p><div class="field"><label>Student Name</label><input id="sName" placeholder="Student Name"></div><div class="field" style="margin-top:12px"><label>Teacher Share Code</label><textarea id="shareCode" rows="5" placeholder="SE1-... অথবা SE0-..."></textarea></div><div class="action-row"><button class="primary" data-action="openStudentPaper">Open Paper →</button></div></div><div class="panel"><h2>Recent Results</h2><div class="list">${studentResults()}</div></div></div>`}
function studentResults(){const arr=read(KEYS.results,[]);if(!arr.length)return '<div class="empty">এখনো কোনো result নেই।</div>';return arr.slice(0,8).map(r=>`<div class="list-item"><div><b>${esc(r.subject)}</b><br><span class="small muted">${esc(r.studentName)} • ${r.score}/${r.total}</span></div><span class="badge">${Math.round(r.score/r.total*100)}%</span></div>`).join('')}
async function openStudentPaper(){const name=$('#sName').value.trim()||'Student';const code=$('#shareCode').value.trim();if(!code)return showToast('Teacher Share Code দিন');try{const payload=await decodeShareCode(code);if(!payload||!payload.questions)return showToast('ভুল বা অসম্পূর্ণ Share Code');state.paperPayload=payload;state.studentName=name;nav('studentExam',{paperPayload:payload,studentName:name})}catch(e){showToast('Share Code পড়া যায়নি')}}
function renderExam(){const p=state.paperPayload;const qs=p.questions||[];if(!qs.length)return nav('student');if(state.examIndex>=qs.length)state.examIndex=qs.length-1;const q=qs[state.examIndex];const answered=state.examAnswers[state.examIndex];app.innerHTML=`<div class="page">${headerBack('Student Exam')}<div class="panel"><div class="toolbar"><div><p class="eyebrow">EXAM</p><h1>${esc(p.teacher.subject)}</h1><p class="muted">Teacher: ${esc(p.teacher.name)} • ${esc(p.teacher.classId)} • Semester ${p.teacher.semester}</p></div><span class="badge" id="timer">05:00</span></div><div class="question-card"><span class="badge">Question ${state.examIndex+1} / ${qs.length}</span><h2>${esc(q.q)}</h2>${q.options.map((o,j)=>`<div class="option exam-option ${answered===j?'selected':''}" data-answer-mode="exam" data-q="${state.examIndex}" data-opt="${j}">${esc(o)}</div>`).join('')}</div><div class="action-row"><button class="secondary" data-action="examPrev" ${state.examIndex===0?'disabled':''}>← Previous</button>${state.examIndex<qs.length-1?'<button class="primary" data-action="examNext">Next →</button>':'<button class="primary" data-action="finishExam">Submit Exam</button>'}</div></div></div>`;if(!state.examStarted){state.examStarted=true;startExamTimer()}}
function startExamTimer(){let end=Date.now()+300000;state.timer=setInterval(()=>{const left=Math.max(0,end-Date.now());const sec=Math.ceil(left/1000);const el=$('#timer');if(el)el.textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;if(sec<=0){clearInterval(state.timer);finishExam()}},250)}
function finishExam(){clearInterval(state.timer);const p=state.paperPayload,qs=p.questions||[];let score=0;qs.forEach((q,i)=>{if(state.examAnswers[i]===Number(q.answer))score++});const result={id:crypto.randomUUID(),studentName:state.studentName||'Student',teacherName:p.teacher.name,teacherCode:p.teacher.code,classId:p.teacher.classId,semester:p.teacher.semester,subject:p.teacher.subject,score,total:qs.length,answers:state.examAnswers,createdAt:Date.now()};const arr=read(KEYS.results,[]);arr.unshift(result);write(KEYS.results,arr);nav('result',{result})}
function renderResult(){const r=state.result;app.innerHTML=`<div class="page"><div class="panel center"><p class="eyebrow">EXAM RESULT</p><h1>${esc(r.subject)}</h1><div class="stats"><div class="stat"><span>Student</span><strong>${esc(r.studentName)}</strong></div><div class="stat"><span>Correct</span><strong>${r.score}</strong></div><div class="stat"><span>Total</span><strong>${r.total}</strong></div><div class="stat"><span>Percentage</span><strong>${Math.round(r.score/r.total*100)}%</strong></div></div><div class="action-row" style="justify-content:center"><button class="primary" data-action="student">Student Home</button><button class="secondary" data-action="profile">Profile</button></div></div></div>`}
function renderComputer(){const cards=['Computer Basics','Keyboard & Mouse','Internet & Safety','MS Office','Programming Basics','Computer Math'];app.innerHTML=`<div class="page">${headerBack('Computer')}<section class="hero"><div><p class="eyebrow">COMPUTER LEARNING</p><h1>Computer <span>Smart Class</span></h1><p>Computer button চাপলে এই interface খুলবে। এখান থেকে subject বেছে Practice করতে পারবেন।</p></div><div class="hero-art"><span class="hero-cap">⌨</span></div></section><div class="subject-grid">${cards.map((x,i)=>`<article class="subject-card"><div class="subject-icon">${['💻','⌨️','🌐','📄','🧑‍💻','➗'][i]}</div><h3>${x}</h3><p>Practice questions and solutions</p><button class="primary" data-computer-subject="${x}">Practice →</button></article>`).join('')}</div></div>`}
function renderProfile(){const p=read(KEYS.teachers,[])[0];const rs=read(KEYS.results,[]);app.innerHTML=`<div class="page">${headerBack('Profile')}<div class="panel center"><div class="avatar" style="margin:auto;width:90px;height:90px;font-size:25px">AK</div><h1>${p?esc(p.name):'Student / User'}</h1><p class="muted">Smart Education profile</p></div><div class="panel"><h2>Results</h2><div class="list">${studentResults()}</div></div></div>`}
function startPractice(s){state.subject=s;nav('practice',{classId:state.classId,semester:state.semester,subject:s})}
function selectAnswer(mode,i,j){if(mode==='practice'){state.practiceAnswers[i]=j;renderPractice()}else if(mode==='exam'){if(state.examAnswers[i]!==undefined)return showToast('এই answer আর পরিবর্তন করা যাবে না');state.examAnswers[i]=j;renderExam()}}
function addQuestion(){syncBuilder();if(state.builderQs.length>=20)return showToast('সর্বোচ্চ ২০টি প্রশ্ন');state.builderQs.push({type:'mcq',q:'',options:['','','',''],answer:0,solution:''});render()}

document.addEventListener('click',async e=>{const a=e.target.closest('[data-action]');if(a){const act=a.dataset.action;if(act==='home')return nav('home');if(act==='theme'){localStorage.setItem(KEYS.theme,document.body.classList.contains('dark')?'light':'dark');setTheme();return}if(act==='language'){showToast('বাংলা / English mode প্রস্তুত');return}if(act==='profile')return nav('profile');if(act==='student')return nav('student');if(act==='teacher')return nav('teacher');if(act==='teacherBuilder')return nav('teacherBuilder');if(act==='computer')return nav('computer');if(act==='back')return nav('home');if(act==='addQuestion')return addQuestion();if(act==='savePaper')return savePaper();if(act==='openStudentPaper')return openStudentPaper();if(act==='examPrev'){state.examIndex--;return renderExam()}if(act==='examNext'){state.examIndex++;return renderExam()}if(act==='finishExam')return finishExam()}
const c=e.target.closest('[data-class]');if(c)return nav('class',{classId:c.dataset.class,semester:1});const pr=e.target.closest('[data-practice]');if(pr)return startPractice(pr.dataset.practice);const so=e.target.closest('[data-solutions]');if(so){state.subject=so.dataset.solutions;return nav('solutions')}const op=e.target.closest('[data-answer-mode]');if(op)return selectAnswer(op.dataset.answerMode,Number(op.dataset.q),Number(op.dataset.opt));const del=e.target.closest('[data-delete-q]');if(del){syncBuilder();state.builderQs.splice(Number(del.dataset.deleteQ),1);return render()};const paper=e.target.closest('[data-paper]');if(paper){const p=read(KEYS.papers,[]).find(x=>x.id===paper.dataset.paper);if(p){state.teacher={id:p.teacherId,name:p.teacherName,code:p.teacherCode,classId:p.classId,semester:p.semester,subject:p.subject};state.builderQs=p.questions;return nav('teacherBuilder')}}const cs=e.target.closest('[data-computer-subject]');if(cs){showToast(`${cs.dataset.computerSubject}: sample practice coming from local question bank`)} });
document.addEventListener('input',e=>{if(e.target.matches('[data-edit-q]')){const i=Number(e.target.dataset.editQ);if(!state.builderQs[i])return;if(e.target.dataset.opt!==undefined)state.builderQs[i].options[Number(e.target.dataset.opt)]=e.target.value;else state.builderQs[i][e.target.dataset.field]=e.target.value}});
(async()=>{try{const r=await fetch(DATA_URL);data=await r.json();render()}catch(e){app.innerHTML='<div class="page"><div class="panel"><h1>Data load error</h1><p>data.json load করতে Live Server ব্যবহার করুন।</p></div></div>'}})();
